Repository yergiroska/system_admin, pull requests merged in 2025-08, with the labels that each got.

#4 3 [Bug][UX] Login no muestra mensaje de error cuando el usuario no existe
  app/Http/Controllers/AuthController.php
  resources/views/auth/login.blade.php
Labels: bug

#10 9 Campos vacíos en tabla de clientes cuando faltan datos, sin mostrar username o email del usuario asociado.
  app/Models/Customer.php
Labels: bug

#12 11 Eliminar atributte de los modelos
  app/Models/Company.php
  app/Models/CompanyProduct.php
  app/Models/Log.php
  app/Models/Note.php
  app/Models/User.php
Labels: invalid

#14 13 Refactor de login y logout
  app/Http/Controllers/AuthController.php
  app/Models/User.php
  app/Models/UserLogin.php
Labels: documentation

#16 15 Limpiar Código
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/CompanyController.php
  app/Http/Controllers/CustomerController.php
  app/Http/Controllers/LogController.php
  app/Http/Controllers/NoteController.php
  app/Http/Controllers/ProductController.php
  app/Models/Company.php
  app/Models/Customer.php
  app/Models/Log.php
  app/Models/Note.php
  app/Models/Product.php
  app/Models/Purchase.php
Labels: duplicate

#18 17 Eliminar Funciones
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/CustomerController.php
  app/Http/Controllers/ProductController.php
  app/Models/Customer.php
Labels: documentation

#23 Agregar campo "imagen del producto" en el formulario de registro de productos
  app/Http/Controllers/ProductController.php
  app/Models/Product.php
  database/migrations/2025_08_30_124447_add_image_url_to_products_table.php
  resources/views/products/create.blade.php
  resources/views/products/edit.blade.php
  resources/views/products/index.blade.php
  resources/views/products/view_products.blade.php
  storage/app/private/.gitignore
  storage/app/public/.gitignore
Labels: enhancement
